---
- name: Install npm ggit vulnerable to command injection in the fetchTags function (CVE-2024-21532)
  hosts: all
  become: yes

  tasks:
    - name: install npm
      apt:
        name:
          - npm
        state: present
        update_cache: yes

    - name: Install Node.js
      ansible.builtin.apt:
        pkg:
          - nodejs
        state: present

    - name: Create /opt/exploit
      file:
        path: /opt/exploit
        state: directory
        mode: '0777'

    - name: Copy exploit.js
      copy:
        src: ./data/exploit.js
        dest: /opt/exploit/exploit.js
        mode: '0777'

    - name: Copy flag.txt
      copy:
        src: ./data/flag.txt
        dest: /opt/exploit/flag.txt
        mode: '0777'

    - name: Copy ggit-2.4.12.tgz
      copy:
        src: ./data/ggit-2.4.12.tgz
        dest: /opt/exploit/ggit-2.4.12.tgz
        mode: '0777'

    - name: Install ggit with npm
      npm:
        name: /opt/exploit/ggit-2.4.12.tgz
        path: /opt/exploit
        state: present