---
- name: Install CVE-2015-1427 PoC based off ElasticSearch
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx
        - docker-compose-v2
        
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"

    - name: Create /opt/ElasticSearch-shell-poc
      file:
        path: /opt/ElasticSearch-shell-poc
        state: directory

    - name: Copy ElasticSearch-shell-poc
      ansible.builtin.copy:
        src: ./data/docker-compose.yml
        dest: /opt/ElasticSearch-shell-poc

    - name: Start Docker Compose services
      command: docker compose up -d --build
      args:
        chdir: /opt/ElasticSearch-shell-poc


