---
- name: Install CVE-2015-1427 PoC based off ElasticSearch
  hosts: all
  become: yes
  tasks:
    - name: Remove docker.io package
      apt:
        name: 
        - docker.io
        - docker-doc
        - docker-compose
        - docker-compose-v2
        - podman-docker
        - containerd
        - runc
        state: absent

    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install prerequisite packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker apt repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt package index after adding Docker repository
      apt:
        update_cache: yes

    - name: Install Docker Engine and related packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
        
    - name: Ensure Docker service is started and enabled
      service:
        name: docker
        state: started
        enabled: yes

    - name: Verify Docker Compose installation
      command: docker compose version
      register: compose_version

    - debug:
        msg: "Docker Compose version: {{ compose_version.stdout }}"

    - name: Create /opt/ElasticSearch-shell-poc
      file:
        path: /opt/ElasticSearch-shell-poc
        state: directory

    - name: Copy ElasticSearch-shell-poc
      ansible.builtin.copy:
        src: ./data/docker-compose.yml
        dest: /opt/ElasticSearch-shell-poc

    - name: Start Docker Compose services
      command: docker compose up -d --build
      args:
        chdir: /opt/ElasticSearch-shell-poc


