---
- name: Setup vulnerable environment for CVE-2019-14287
  hosts: all
  become: yes
  vars:
    sudo_version: "1.8.0"  

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install build dependencies
      apt:
        pkg:
          - build-essential
          - make
          - gcc

    - name: Copy sudo source
      copy:
        src: "./data/sudo-{{ sudo_version }}.tar.gz"
        dest: "/root/sudo-{{ sudo_version }}.tar.gz"

    - name: Extract sudo source
      unarchive:
        src: "/root/sudo-{{ sudo_version }}.tar.gz"
        dest: /root/
        remote_src: yes

    - name: Configure sudo
      command: ./configure
      args:
        chdir: "/root/sudo-{{ sudo_version }}"

    - name: Build sudo
      command: make
      args:
        chdir: "/root/sudo-{{ sudo_version }}"

    - name: Install sudo
      command: make install
      args:
        chdir: "/root/sudo-{{ sudo_version }}"

    - name: Create hacker user
      user:
        name: hacker
        create_home: yes

    - name: Configure sudoers with exploit permissions
      lineinfile:
        path: /etc/sudoers
        line: 'hacker ALL=(ALL,!root) /bin/bash'
        validate: 'visudo -cf %s'

    - name: Copy exploit script to hacker's home
      copy:
        src: "./data/sudo_exploit.py"
        dest: "/home/hacker/sudo_exploit.py"
        mode: "0755"
        owner: hacker
