---
- name: Set up bashdoor vulnerability with apache2 and bash 4.2
  hosts: all
  become: yes
  vars:
    bash_version: "4.2"
    install_dir: "/usr/local/src"
    bash_src_file: "./data/bash-{{ bash_version }}.tar.gz"  # Update this with your file path
    bash_src_dir: "{{ install_dir }}/bash-{{ bash_version }}"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - build-essential
        - tar

    - name: Copy Bash source code to target
      copy:
        src: "{{ bash_src_file }}"
        dest: "{{ install_dir }}/bash-{{ bash_version }}.tar.gz"

    - name: Extract Bash source code
      ansible.builtin.unarchive:
        src: "{{ install_dir }}/bash-{{ bash_version }}.tar.gz"
        dest: "{{ install_dir }}"
        remote_src: yes

    - name: Compile Bash from source
      command:
        cmd: "{{ item }}"
        chdir: "{{ bash_src_dir }}"
      loop:
        - ./configure
        - make
        - make install

    - name: Verify Bash version
      command:
        cmd: /usr/local/bin/bash --version
      register: bash_version_output

    - name: Display Bash version
      debug:
        msg: "{{ bash_version_output.stdout_lines }}"
    - name: Install Apache2
      apt:
        name: apache2
        state: present

    - name: Enable CGI module
      command: a2enmod cgi

    - name: Restart Apache2 to apply changes
      systemd:
        name: apache2
        state: restarted
    - name: Copy 000-default.conf to Apache2 sites-available
      copy:
        src: ./data/000-default.conf
        dest: /etc/apache2/sites-available/000-default.conf

    - name: Enable new site configuration
      command: a2ensite 000-default.conf

    - name: Reload Apache2 to apply changes
      systemd:
        name: apache2
        state: reloaded
    - name: Copy cgi-script.sh to /usr/lib/cgi-bin
      copy:
        src: ./data/cgi-script.sh
        dest: /usr/lib/cgi-bin/cgi-script.sh
        mode: '0755'