---
- name: Install Basic Spring Application with CVE-2022-22965 
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx

    - name: Create /opt/spring4shell
      file:
        path: /opt/spring4shell
        state: directory

    - name: Copy spring4shell
      ansible.builtin.copy:
        src: ./data/spring4shell/
        dest: /opt/spring4shell

    - name: Build spring4shell Docker container
      community.docker.docker_image_build:
        name: spring4shell:latest
        path: /opt/spring4shell

    - name: Run spring4shell Docker container
      community.docker.docker_container:
        name: spring4shell
        image: spring4shell:latest
        state: started
        ports:
          - "8080:8080"


