---
- name: Install the exploit for Spring4Shell Vulnerability（CVE-2022-22965）
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes
        
    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - python3-pip

    - name: Create /opt/spring4shell
      file:
        path: /opt/spring4shell
        state: directory

    - name: Copy spring4shell
      ansible.builtin.copy:
        src: ./data/spring4shell/
        dest: /opt/spring4shell

    - name: Install packages required for spring4shell
      ansible.builtin.shell:
        cmd: pip3 install requests
        chdir: /opt/spring4shell
