- name: Setup and run the vulnerable and misconfigured version of Apache
  hosts: all
  become: true
  vars:
    apache_version: "2.4.50"
    external_directory: "/var/apache"
    cgi_directory: "/var/apache/cgi-bin"
  tasks:
    - name: Ensure dependencies are installed
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - build-essential
        - libpcre3
        - libpcre3-dev
        - libssl-dev
        - libapr1-dev 
        - libaprutil1-dev
    - name: Download Apache HTTP Server {{ apache_version }}
      get_url:
        url: "https://archive.apache.org/dist/httpd/httpd-{{ apache_version }}.tar.gz"
        dest: "/tmp/httpd-{{ apache_version }}.tar.gz"
    - name: Extract Apache HTTP Server
      unarchive:
        src: "/tmp/httpd-{{ apache_version }}.tar.gz"
        dest: "/tmp"
        remote_src: yes
    - name: Compile and Install Apache
      shell: |
        cd /tmp/httpd-{{ apache_version }}
        ./configure --prefix=/usr/local/apache2 --enable-so --enable-cgi --enable-alias
        make
        make install
      args:
        creates: "/usr/local/apache2/bin/httpd"
    - name: Create external directory for alias
      file:
        path: "{{ external_directory }}"
        state: directory
        mode: "0755"
    - name: Create CGI directory
      file:
        path: "{{ cgi_directory }}"
        state: directory
        mode: "0755"
    - name: Configure Apache to allow
      blockinfile:
        path: "/usr/local/apache2/conf/httpd.conf"
        marker: "{mark}"
        marker_begin: "<Directory />"
        marker_end: "</Directory>"
        block: |-
            AllowOverride none
        state: present
    - name: Configure Apache with Alias and Vulnerable Settings
      blockinfile:
        path: "/usr/local/apache2/conf/httpd.conf"
        insertafter: "DocumentRoot \"/usr/local/apache2/htdocs\""
        block: |
          Alias /external/ "{{ external_directory }}/"
          <Directory "{{ external_directory }}">
              Options Indexes FollowSymLinks ExecCGI
              AllowOverride None
              Require all granted
          </Directory>
          ScriptAlias /cgi-bin/ "{{ cgi_directory }}/"
    - name: Start Apache server
      command: "/usr/local/apache2/bin/apachectl start"
      args:
        creates: "/usr/local/apache2/logs/httpd.pid"
    - name: Enable Apache to start on boot
      copy:
        dest: /etc/systemd/system/apache2.service
        content: |
          [Unit]
          Description=The Apache HTTP Server
          After=network.target

          [Service]
          ExecStart=/usr/local/apache2/bin/apachectl start
          ExecReload=/usr/local/apache2/bin/apachectl graceful
          ExecStop=/usr/local/apache2/bin/apachectl stop
          PIDFile=/usr/local/apache2/logs/httpd.pid
          Type=forking

          [Install]
          WantedBy=multi-user.target
      notify: Enable and start apache2
  handlers:
    - name: Enable and start apache2
      systemd:
        name: apache2
        enabled: yes
        state: started