---
- name: Set up Apache HTTP Server
  hosts: all
  become: yes

  tasks:
    - name: Update the package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name: 
          - wget
          - curl
          - make
          - gcc
          - perl
          - libapr1-dev
          - libaprutil1-dev
          - libpcre3-dev
        state: present

    - name: Copy tarball
      copy:
        src: ./data/httpd-2.4.49.tar.gz
        dest: /tmp
        mode: '0644'

    - name: Extract Apache HTTP Server tarball
      unarchive:
        src: /tmp/httpd-2.4.49.tar.gz
        dest: /tmp
        remote_src: yes

    - name: Configure Apache HTTP Server
      command: ./configure --prefix=/
      args:
        chdir: /tmp/httpd-2.4.49

    - name: Compile Apache HTTP Server
      command: make
      args:
        chdir: /tmp/httpd-2.4.49

    - name: Install Apache HTTP Server
      command: make install
      args:
        chdir: /tmp/httpd-2.4.49

    - name: Copy custom httpd configuration
      copy:
        src: ./data/httpd.conf
        dest: /conf/httpd.conf

    - name: Start Apache HTTP Server
      command: apachectl -k start