---
- name: Install Tensorflow 2.11.1 + deps, and copy exploit/victim scripts
  hosts: all
  become: yes

  tasks:
    - name: Install pip and venv
      apt:
        name:
          - python3-pip
        state: present
        update_cache: yes

    - name: Upgrade pip
      pip:
        name: pip
        state: latest
        executable: pip3

    - name: Create /opt/exploit
      file:
        path: /opt/exploit
        state: directory
        mode: '0777'

    - name: Copy data to VM
      copy:
        src: ./data/
        dest: /opt/exploit/

    - name: Install packages from .whl
      ansible.builtin.command: >
        pip install --no-index --ignore-installed --find-links /opt/exploit/pipdownloads
        -r /opt/exploit/pipdownloads/requirements.txt
      become: yes


