---
- name: Install Apache Tomcat vulnerable to AJP Arbitrary File Read/Include（CVE-2020-1938）
  hosts: all
  become: yes
  vars:
    tomcat_version: "9.0.30"
    install_dir: "/opt/tomcat"
    tomcat_user: "tomcat"
    tomcat_group: "tomcat"
    java_package: "openjdk-11-jre-headless"

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install dependencies (Java and utilities)
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - curl
        - wget
        - tar
        - "{{ java_package }}"

    - name: Create tomcat group
      group:
        name: "{{ tomcat_group }}"

    - name: Create tomcat user
      user:
        name: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        home: "{{ install_dir }}"
        shell: /bin/false

    - name: Create installation directory for Tomcat
      file:
        path: "{{ install_dir }}"
        state: directory
        mode: '0755'

    - name: Extract apache-tomcat-9.0.30.tar.gz
      ansible.builtin.unarchive:
        src: ./data/apache-tomcat-9.0.30.tar.gz
        dest: "{{ install_dir }}"
        creates: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"

    - name: Create symbolic link for Tomcat installation
      file:
        src: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"
        dest: "{{ install_dir }}/latest"
        state: link

    - name: Change ownership of the Tomcat directory
      file:
        path: "{{ install_dir }}/apache-tomcat-{{ tomcat_version }}"
        state: directory
        owner: "{{ tomcat_user }}"
        group: "{{ tomcat_group }}"
        recurse: yes

    - name: Set environment variables for Tomcat
      lineinfile:
        path: /etc/environment
        line: "{{ item }}"
        create: yes
      loop:
        - "CATALINA_HOME={{ install_dir }}/latest"
        - "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"

    - name: Create systemd service for Tomcat
      copy:
        dest: /etc/systemd/system/tomcat.service
        content: |
          [Unit]
          Description=Apache Tomcat
          After=network.target

          [Service]
          Type=forking

          User={{ tomcat_user }}
          Group={{ tomcat_group }}
          Environment="JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64"
          Environment="CATALINA_PID={{ install_dir }}/latest/temp/tomcat.pid"
          Environment="CATALINA_HOME={{ install_dir }}/latest"
          Environment="CATALINA_BASE={{ install_dir }}/latest"
          ExecStart={{ install_dir }}/latest/bin/startup.sh
          ExecStop={{ install_dir }}/latest/bin/shutdown.sh

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd daemon
      systemd:
        daemon_reload: yes

    - name: Start and enable Apache Tomcat
      systemd:
        name: tomcat
        enabled: yes
        state: started

