---
- name: Install CVE-2021-44228 PoC based off Tomcat
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx

    - name: Create /opt/log4j-shell-poc
      file:
        path: /opt/log4j-shell-poc
        state: directory

    - name: Copy log4j-shell-poc
      ansible.builtin.copy:
        src: ./data/log4j-shell-poc/
        dest: /opt/log4j-shell-poc

    - name: Build log4j-shell-poc Docker container
      community.docker.docker_image_build:
        name: log4j-shell-poc:latest
        path: /opt/log4j-shell-poc

    - name: Run log4j-shell-poc Docker container
      community.docker.docker_container:
        name: log4j-shell-poc
        image: log4j-shell-poc:latest
        state: started
        ports:
          - "8080:8080"


