blueprint: ubuntu2204-ubuntu2204
ubuntu1:
  playbook: ubuntu1.yml
  command:
    -  "/opt/jquerydocker/install.sh"
ubuntu2:
  playbook: ubuntu2.yml
  command:
    - "/opt/exploit/CVE-2018-9206.sh http://%ubuntu1%:8000/jQuery-File-Upload-9.22.0/"
