---
- name: Install the CVE-2018-9206 dockerfile
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx

    - name: Create /opt/jquerydocker
      file:
        path: /opt/jquerydocker
        state: directory

    - name: Copy jquerydocker
      ansible.builtin.copy:
        src: ./data/jquerydocker/
        dest: /opt/jquerydocker

    - name: Start Docker service
      service:
        name: docker
        state: started
      
    - name: Build jquerydocker Docker container
      community.docker.docker_image:
        name: jquerydocker:latest
        source: build
        build:
          path: /opt/jquerydocker

    - name: Run jquerydocker Docker container
      community.docker.docker_container:
        name: jquerydocker
        image: jquerydocker:latest
        ports:
          - "8000:80"
        detach: true

