---
- name: Install CVE-2021-44228 PoC based off Tomcat
  hosts: all
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present

    - name: Install a list of packages
      ansible.builtin.apt:
        pkg:
        - docker-buildx

    - name: Create /opt/jquerydocker
      file:
        path: /opt/jquerydocker
        state: directory

    - name: Copy jquerydocker
      ansible.builtin.copy:
        src: ./data/jquerydocker/
        dest: /opt/jquerydocker

    - name: Set execute permission for the exploit script
      file:
        path: /opt/jquerydocker/install.sh
        mode: '0755'

    - name: Start Docker service
      service:
        name: docker
        state: started
      
    - name: Run install.sh
      shell: bash /opt/jquerydocker/install.sh