blueprint: ubuntu2204
ubuntu:
  trace: nginx
  playbook: ubuntu.yml
  command:
    - "sudo chown -R vagrant:vagrant /home/vagrant/apache-tomcat-9.0.0.M1"  
    - "sudo chmod -R 755 /home/vagrant/apache-tomcat-9.0.0.M1"
    - "sed -i.bak 's/>listings</>readonly</g' /home/vagrant/apache-tomcat-9.0.0.M1/conf/web.xml"
    - "cat /home/vagrant/apache-tomcat-9.0.0.M1/conf/web.xml | grep -A 5 -B 5 readonly"
    - "cd /home/vagrant/apache-tomcat-9.0.0.M1/bin && ./startup.sh&~~~Tomcat started"
    - "sleep 10"  # Wait for Tomcat to fully start
    - "sudo chmod 755 /home/vagrant/data/exploit.py"
    - "sudo chmod -R 755 /home/vagrant/data"
    - "python3 /home/vagrant/data/exploit.py -u http://%ubuntu%:8080"
