- hosts: ubuntu
  become: yes
  tasks:
    - name: Create data directory
      file:
        path: /home/vagrant/data
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'
      
    - name: Install Java and Dependencies
      apt:
        name: 
          - default-jdk
          - python3
          - python3-pip
        state: present
        update_cache: yes

    - name: Install Python Requests Library
      pip:
        name: requests
        state: present

    - name: Copy Tomcat Binary
      copy:
        src: data/apache-tomcat-9.0.0.M1.tar.gz
        dest: /home/vagrant/apache-tomcat-9.0.0.M1.tar.gz

    - name: Extract Tomcat
      unarchive:
        src: /home/vagrant/apache-tomcat-9.0.0.M1.tar.gz
        dest: /home/vagrant/
        remote_src: yes

    - name: Ensure Tomcat startup script is executable
      file:
        path: /home/vagrant/apache-tomcat-9.0.0.M1/bin/startup.sh
        mode: '+x'

    - name: Copy Exploit Script
      copy:
        src: data/exploit.py
        dest: /home/vagrant/data/exploit.py
        mode: '+x'